Design story backend+frontend
TransformerOptimus/SuperCoder pull request #25
Opened 2024-07-05 17:12 UTC by rounak610

2024-07-05 19:45 UTC, sasikanthlanka requested changes

2024-07-05 19:45 UTC, sasikanthlanka commented on app/services/s3_providers/s3_service.go
> +	fmt.Println("awsAccessKeyID:", awsAccessKeyID)
Remove logging of credentials

2024-07-05 19:49 UTC, sasikanthlanka requested changes

2024-07-05 19:49 UTC, sasikanthlanka commented on executor.go
> +		log.Println("Claude API Key:", apiKey)
Remove api key logging, also remove creating singleton claude client altogether. Create new instance with customer key where ever possible.

2024-07-06 12:40 UTC, rounak610 commented on app/services/s3_providers/s3_service.go
> +	fmt.Println("awsAccessKeyID:", awsAccessKeyID)
removed

2024-07-06 12:40 UTC, rounak610 commented on executor.go
> +		log.Println("Claude API Key:", apiKey)
removed

2024-07-10 05:38 UTC, closed without merging